repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
    - id: go-mod-tidy-repo
      verbose: true
    - id: go-fmt
      args: [-w]
      verbose: true
    - id: go-test-repo-mod
      args: [--count=1]
      verbose: true
